config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace(:admin) do
    resources :users do
      resources :wholesalers, only: [:update, :create, :edit, :new, :destroy]
    end

    resources :wholesalers, only: :index

    resource :wholesale_configurations, only: [:update, :edit]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do

      namespace :storefront do
        resources :wholesalers, only: [:show, :index]
      end
    end
  end

end

app/models/spree/wholesaler.rb
module Spree
  class Wholesaler < ActiveRecord::Base
    belongs_to :user, class_name: Spree.user_class.to_s
    belongs_to :business_address, dependent: :destroy, class_name: "Spree::BusinessAddress"
    validates :main_contact, presence: true

    accepts_nested_attributes_for :business_address
    
    delegate :email, to: :user
    delegate :company, :phone, to: :find_or_build_business_address

    def find_or_build_business_address
      business_address ||= build_business_address(country: Spree::Country.new)
    end
  end
end

app/controllers/spree/admin/wholesalers_controller.rb
module Spree
  module Admin
    class WholesalersController < ResourceController
      before_action :load_user, except: :index

      def edit
        @wholesaler = Spree::Wholesaler.find(params[:id])
      end

      def new
        @wholesaler = @user.build_wholesaler
      end

      def create
        @wholesaler = Spree::Wholesaler.new(wholesaler_params)
        if @wholesaler.save
          flash[:notice] = I18n.t('spree.spree_wholesale_storefront.success')
          redirect_to spree.edit_admin_user_path(id: @wholesaler.user_id)
        else
          flash[:error] = I18n.t('spree.spree_wholesale_storefront.failed')
          flash[:error] = @wholesaler.errors.full_messages.to_sentence
          redirect_to spree.edit_admin_user_path(id: @wholesaler.user_id)
        end
      end

      def update
        @wholesaler = Spree::Wholesaler.find(params[:id])
        if @wholesaler.update_attributes(wholesaler_params)
          flash[:notice] = I18n.t('spree.spree_wholesale_storefront.update_success')
        else
          flash[:error] = I18n.t('spree.spree_wholesale_storefront.update_failed')
          flash[:error] = @wholesaler.errors.full_messages.to_sentence
        end
        redirect_to spree.edit_admin_user_path(id: @wholesaler.user_id)
      end

      def destroy
        @wholesaler = Spree::Wholesaler.find(params[:id])
        @wholesaler.destroy
        flash[:notice] = I18n.t('spree.spree_wholesale_storefront.destroy_success')
        redirect_to spree.edit_admin_user_path(id: @wholesaler.user_id)
      end

      private

      def load_user
        @user ||= ::Spree.user_class.find(params[:user_id])
      end
      
      def collection
        return @collection if @collection.present?

        @collection = ::Spree.user_class.where(nil)
        @search = @collection.ransack(params[:q])
        @collection = @search.result.wholesale.page(params[:page]).per(::Spree::Config[:admin_users_per_page])
      end

      def wholesaler_params
        params.require(:wholesaler).permit([
          :main_contact, :alternate_contact, :web_address, :notes, :user_id, :alternate_email,
          :business_address_attributes => [
            :address1, :address2, :city, :zipcode, :phone, :state_name, :alternative_phone, :company, :state_id, :country_id
          ]
        ])
      end      
    end
  end
end

app/controllers/spree/api/v2/storefront/wholesalers_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        class WholesalersController < ::Spree::Api::V2::BaseController
          include Spree::Api::V2::CollectionOptionsHelpers

          def index
            render_serialized_payload { serialize_collection(paginated_collection) }
          end

          def show
            render_serialized_payload { serialize_resource(resource) }
          end

          private

          # def serialize_wholesaler(wholesaler)
          #   Spree::V2::Storefront::GiftCardSerializer.new(wholesaler, include: resource_includes, fields: sparse_fields).serializable_hash
          # end

          # def render_wholesaler(result)
          #   if result.success?
          #     render_serialized_payload { serialized_current_order }
          #   else
          #     render_error_payload(result.error)
          #   end
          # end

          # THIS HAS BEEN MOVED TO BASE CONTROLLER
          def serialize_resource(resource)
            resource_serializer.new(
              resource,
              include: resource_includes,
              fields: sparse_fields
            ).serializable_hash
          end

          def serialize_collection(collection)
            collection_serializer.new(
              collection,
              collection_options(collection)
            ).serializable_hash
          end

          def collection_options(collection)
            {
              links: collection_links(collection),
              meta: collection_meta(collection),
              include: resource_includes,
              fields: sparse_fields
            }
          end

          def resource
            scope.find(params[:id])
          end

          def resource_serializer
            Spree::V2::Storefront::WholesalerSerializer
          end

          def paginated_collection
            collection_paginator.new(collection, params).call
          end

          def collection
            Spree::Wholesaler.all
          end
  
          def collection_paginator
            Spree::Api::Dependencies.storefront_collection_paginator.constantize
          end

          def collection_serializer
            Spree::V2::Storefront::WholesalerSerializer
          end

          def scope
            Spree::Wholesaler.accessible_by(current_ability, :show).includes(scope_includes)
          end

          def current_ability
            @current_ability ||= Spree::WholesalerAbility.new(spree_current_user)
          end

          def scope_includes
            {
              user: {},
              business_address: {}
            }
          end
        end
      end
    end
  end
end

app/views/spree/admin/wholesalers/_address_fields.erb
<%= field_container f.object, :company, class: ["form-group", "business-row"] do %>
  <%= f.label :company, Spree.t(:company) %><span class="req"> *</span>
  <%= f.text_field :company, class: 'form-control' %>
  <%= error_message_on f.object, :company %>
<% end %>

<%= field_container f.object, :address1, class: ["form-group", "business-row"] do %>
  <%= f.label :address1, Spree.t(:street_address) %><span class="req"> *</span>
  <%= f.text_field :address1, class: 'form-control' %>
  <%= error_message_on f.object, :address1 %>
<% end %>

<%= field_container f.object, :address2, class: ["form-group", "business-row"] do %>
  <%= f.label :address2, Spree.t(:street_address_2) %>
  <%= f.text_field :address2, class: 'form-control' %>
  <%= error_message_on f.object, :address2 %>
<% end %>

<%= field_container f.object, :city, class: ["form-group", "business-row"] do %>
  <%= f.label :city, Spree.t(:city) %><span class="req"> *</span>
  <%= f.text_field :city, class: 'form-control' %>
  <%= error_message_on f.object, :city %>
<% end %>

<%= field_container f.object, :zipcode, class: ["form-group", "business-row"] do %>
  <%= f.label :zipcode, Spree.t(:zip) %><span class="req"> *</span>
  <%= f.text_field :zipcode, class: 'form-control' %>
  <%= error_message_on f.object, :zipcode %>
<% end %>

<div class="form-group <%= "business-row" %>">
  <%= f.label :country_id, Spree.t(:country) %><span class="req"> *</span>
  <span id="business_country">
    <%= f.collection_select :country_id, available_countries, :id, :name, {}, { class: 'select2' } %>
  </span>
</div>

<%= field_container f.object, :state, class: ["form-group", "business-row"] do %>
  <%= f.label :state_id, Spree.t(:state) %><span class="req"> *</span>
  <span id="business_state">
    <%= f.text_field :state_name,
          style: "display: #{f.object.country.states.empty? ? 'block' : 'none' };",
          disabled: !f.object.country.states.empty?, class: 'form-control state_name' %>
    <%= f.collection_select :state_id, f.object.country.states.sort, :id, :name, { include_blank: true }, { class: 'select2', style: "display: #{f.object.country.states.empty? ? 'none' : 'block' };", disabled: f.object.country.states.empty? } %>
  </span>
  <%= error_message_on f.object, :state_id %>
<% end %>

<%= field_container f.object, :phone, class: ["form-group", "business-row"] do %>
  <%= f.label :phone, Spree.t(:phone) %><span class="req"> *</span>
  <%= f.phone_field :phone, class: 'form-control' %>
  <%= error_message_on f.object, :phone %>
<% end %>

<% content_for :head do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('span#business_country .select2').on('change', function() { update_state('business_'); });
    });
  <% end %>
<% end %>

app/views/spree/admin/wholesalers/_fields.html.erb
<!-- <%= render "spree/shared/error_messages", :target => @wholesaler %> -->
<div class="row wholesaler-details ">
  <div class="col-12 col-md-6">
    <%= f.hidden_field :user_id %>
    <div class="form-group">
      <%= f.label :main_contact %><span class="req">*</span>
      <%= f.text_field :main_contact, :class => 'form-control required' %>
    </div>
    <div class="form-group">
      <%= f.label :alternate_contact %>
      <%= f.text_field :alternate_contact, :class => 'form-control required' %>
    </div>
    <div class="form-group">
      <%= f.label :alternate_email %>
      <%= f.text_field :alternate_email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :web_address %>
      <%= f.text_field :web_address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :notes %>
      <%= f.text_area :notes, class: 'form-control', rows: '4' %>
    </div>
  </div>
  <div class="col-12 col-md-6">
    <%= f.fields_for :business_address, (@wholesaler.business_address || Spree::BusinessAddress.default(@wholesaler, "business")) do |ba_form| %>
      <% ba_form.object ||= Spree::BusinessAddress.new(country: Spree::Country.new) %>
      <%= render partial: 'spree/admin/wholesalers/address_fields', locals: { f: ba_form } %>
    <% end %>
  </div>
</div>

app/views/spree/admin/wholesalers/_tab.html.erb
<% if Spree.user_class && can?(:admin, Spree.user_class) %>
  <ul class='nav nav-sidebar border-bottom'>
    <%= tab "Wholesalers", url: spree.admin_wholesalers_url, method: :get, icon: 'briefcase' %>
  </ul>
<% end %>

app/views/spree/admin/wholesalers/_wholesale_price_field.erb
<div data-hook="admin_product_form_wholesale_price">
  <%= f.field_container :wholesale_price, class: ['form-group'] do %>
    <%= f.label :wholesale_price, Spree.t('spree.spree_wholesale_storefront.wholesale_price') %>
    <%= f.text_field :wholesale_price, value: number_to_currency(@product.wholesale_price, unit: ''), class: 'form-control', disabled: (cannot? :update, @product.master.wholesale_price) %>
    <%= f.error_message_on :wholesale_price %>
  <% end %>
</div>

app/views/spree/admin/wholesalers/edit.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :wholesaler, id: @user.id } %>

<% content_for :page_title do %>
  <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
  <%= Spree.t('spree_wholesale_storefront.edit_wholesaler') %>
<% end %>

<div data-hook="admin_user_wholesaler_form" class="card mb-3">
  <div class="card-header">
    <div class="row ml-1 pb-0">
      <div class="col-6">
        <h1 class="card-title mb-0 h5">
          Wholesaler Account Details
        </h1>
      </div>
      <div class="col-6">
        <% if !@wholesaler.new_record? %>
          <%= form_for @wholesaler, url: spree.admin_user_wholesaler_path(@user, @wholesaler), method: :delete, :html => { :class => "wholesaler-form pull-right float-right" } do |f| %>
            <%= button_to "Delete Account", spree.admin_user_wholesaler_path(@user, @wholesaler),
              :method => :delete,
              class: "btn btn-danger",
              data: { confirm: Spree.t(:are_you_sure), action: 'remove' }%>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
  <div class="card-body" id="edit_wholesaler_form">
    <%= form_for [:admin, @user, @wholesaler], url: spree.admin_user_wholesaler_path(@user, @wholesaler), :html => { :class => "wholesaler-form" } do |f| %>
      
      <%= render partial: 'spree/admin/wholesalers/fields', locals: { f: f } %>

      <div data-hook="admin_user_edit_form_button">
        <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_users_url } %>
      </div>

    <% end %>
  </div>  
</div>

app/views/spree/admin/wholesalers/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:wholesalers, scope: :spree_wholesale_storefront) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_user), new_admin_user_url, class: "btn-success", icon: 'add', id: 'admin_new_user_link' %>
<% end if can? :create, Spree::user_class %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_users_index_search">
    <%= search_form_for [:admin, @search], url: spree.admin_users_url do |f| %>
      <div class="form-group">
        <%= f.label :email_cont, Spree.t(:email) %>
        <%= f.text_field :email_cont, class: "form-control js-quick-search-target js-filterable" %>
      </div>
      <div class="row">
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <%= f.label :bill_address_firstname_cont, Spree.t(:first_name) %>
            <%= f.text_field :bill_address_firstname_cont, class: 'form-control js-filterable' %>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <%= f.label :bill_address_lastname_cont, Spree.t(:last_name) %>
            <%= f.text_field :bill_address_lastname_cont, class: 'form-control js-filterable' %>
          </div>
        </div>
      </div>
      <% if Spree::Config[:company] %>
        <div class="form-group">
          <%= f.label :bill_address_company_cont, Spree.t(:company) %>
          <%= f.text_field :bill_address_company_cont, class: 'form-control js-filterable' %>
        </div>
      <% end %>
      <div data-hook="admin_users_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<% if @wholesalers.any? %>
  <table class="table" id="listing_users" data-hook>
    <thead>
      <tr data-hook="admin_users_index_headers">
        <th>
          <%= sort_link @search,:email, Spree.t(:user), {}, {title: 'users_email_title'} %>
        </th>
        <th data-hook="admin_users_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @wholesalers.each do |user|%>
        <tr id="<%= spree_dom_id user %>" data-hook="admin_users_index_rows">
          <td class='user_email'><%=link_to user.email, edit_admin_user_url(user) %></td>
          <td data-hook="admin_users_index_row_actions" class="actions actions-2 text-right">
            <%= link_to_edit_url edit_admin_user_url(user), no_text: true if can?(:edit, user) %>
            <%= link_to_with_icon 'delete', '', admin_user_url(user),{ name: Spree.t(:delete), no_text: true,
              class: 'btn btn-danger btn-sm delete-resource', data: { confirm: Spree.t(:are_you_sure), action: 'remove' }} if can?(:edit, user) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree.user_class)) %>,
    <%
=begin%>
 <%= link_to Spree.t(:add_one), new_object_url %>! 
<%
=end%>
  </div>
<% end %>

<%# <%= paginate @wholesalers, theme: 'twitter-bootstrap-4' %> %>
<%= paginate @wholesalers %>

app/views/spree/admin/wholesalers/new.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :wholesaler } %>
<% content_for :page_title do %>
  <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
  <%= Spree.t('spree_wholesale_storefront.new_wholesaler') %>
<% end %>

<div data-hook="admin_user_wholesaler_form" class="card mb-3">
  <div class="card-header">
    <div class="row ml-1 pb-0">
      <div class="col-xs-6">
        <h1 class="card-title mb-0 h5">
          Wholesaler Account Details
        </h1>
      </div>
    </div>
  </div>
  <div class="card-body">
    <%= form_for [:admin, @user, @wholesaler], url: spree.admin_user_wholesalers_url, method: :post, :html => { :class => "wholesaler-form" } do |f| %>
      <%= render partial: 'spree/admin/wholesalers/fields', locals: { f: f } %>

      <div data-hook="admin_user_wholesaler_new_form_buttons">
        <%= render partial: 'spree/admin/shared/new_resource_links', locals: {collection_url: spree.admin_users_url} %>
      </div>
    <% end %>
  </div>
</div>