config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace(:admin) do
    resources :users do
      resources :wholesalers, only: [:update, :create, :edit, :new, :destroy]
    end

    resources :wholesalers, only: :index

    resource :wholesale_configurations, only: [:update, :edit]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do

      namespace :storefront do
        resources :wholesalers, only: [:show, :index]
      end
    end
  end

end

app/models/spree/wholesale_configuration.rb
module Spree
  class WholesaleConfiguration < Preferences::Configuration
    preference :minimum_order, :decimal, default: 300.0
    preference :google_map_api_key, :string, default: ''
  end
end

app/controllers/spree/admin/wholesale_configurations_controller.rb
module Spree
  module Admin
    class WholesaleConfigurationsController < ResourceController

      def update
        config = Spree::WholesaleConfiguration.new
        @preferences = params && params.key?(:preferences) ? params.delete(:preferences) : params
        @preferences.each do |name, value|
          next unless config.has_preference? name
          config[name] = value
        end
        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:wholesale_configuration, scope: :spree_wholesale_storefront))
        redirect_to edit_admin_wholesale_configurations_path
      end
    end
  end
end

app/views/spree/admin/wholesale_configurations/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:wholesale_configurations, scope: :spree_wholesale_storefront) %>
<% end %>

<%= form_tag admin_wholesale_configurations_path, method: :put do %>
	<div class="row">
		<div class="col-md-12" data-hook="wholesales">
			<div class="form-group">
				<%= label_tag :minimum_order do %>
					<%= preference_field_tag :minimum_order, Spree::WholesaleStorefront::Config[:minimum_order], type: :decimal, class: "form-control" %>
					<%= Spree.t(:minimum_order, scope: :spree_wholesale_storefront) %>
				<% end %>
			</div>

			<div class="form-group">
				<%= label_tag :google_map_api_key do %>
					<%= preference_field_tag :google_map_api_key, Spree::WholesaleStorefront::Config[:google_map_api_key], type: :string, size: 50, class: "form-control" %>
					<%= Spree.t(:google_map_api_key, scope: :spree_wholesale_storefront) %>
				<% end %>
			</div>

			<div class="form-actions" data-hook="buttons">
				<%= button Spree.t('actions.update'), 'update' %>
			</div>
		</div>
	</div>
<% end %>